serviceMonitor:
  enabled: true
  # serviceMonitor.labels -- labels to set on the vault serviceMonitor
  labels: {}
  # scrapeTimeout  -- scrapeTimeout of the serviceMonitor
  scrapeTimeout: 30s

  scrapeInterval: 30s

  # -- Specify the Kubernetes namespace where Prometheus expects to find
  # service monitors configured.
  # namespace: ""


prometheus:
  # -- Create prometheus-operator resources
  enabled: true
  rule:
    # -- Optional Namespace for PrometheusRule resource
    namespace: ""
    # -- Additional Labels for PrometheusRule resource
    additionalLabels: {}
    alerts:
      horizontalPodAutoscalerIsNotActive:
        enabled: true
        severity: warning
      horizontalPodAutoscalerIsNotAbleToScale:
        enabled: true
        severity: warning
      podIsOOMKilled:
        enabled: true
        severity: warning
        timeInterval: 1h

    additionalAlerts: []
    # - alert: CertManagerCertificateReadyStatus
    #   annotations:
    #     description: 'Failed node exist in cluster'
    #     summary: Number Of Failed Nodes above zero
    #   expr: (avg(kube_node_count_total) OR on() vector(0)) - (count(kube_node_status{condition="ready"}==1) OR on() vector(0)) == 1
    #   labels:
    #     severity: critical

grafana:
  # -- Enable deploying cert-manager dashboard to Grafana
  enabled: false
  # -- Add `grafana_dashboard: "1"` default label
  defaultLabel: true
  # -- Extra labels for dashboard ConfigMap
  extraLabels: {}
  # -- Extra annotations for dashboard ConfigMap
  extraAnnotations: {}
